# Generated by Django 5.1.2 on 2025-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuadreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('billetes_100mil', models.IntegerField(default=0)),
                ('billetes_50mil', models.IntegerField(default=0)),
                ('billetes_20mil', models.IntegerField(default=0)),
                ('billetes_10mil', models.IntegerField(default=0)),
                ('billetes_5mil', models.IntegerField(default=0)),
                ('billetes_2mil', models.IntegerField(default=0)),
                ('billetes_1mil', models.IntegerField(default=0)),
                ('monedas_500', models.IntegerField(default=0)),
                ('monedas_200', models.IntegerField(default=0)),
                ('monedas_100', models.IntegerField(default=0)),
                ('monedas_50', models.IntegerField(default=0)),
                ('total_efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_caja', models.DecimalField(decimal_places=2, default=150000, max_digits=10)),
                ('valor_qr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nomina', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_entregar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
