# Generated by Django 5.1.2 on 2025-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrecaja',
            name='dia_cuadre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
