# Generated by Django 5.1.2 on 2025-02-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descripcion_descuento',
            field=models.TextField(blank=True, help_text='Motivo del descuento', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje (ej. 10 para 10%)', max_digits=5),
        ),
    ]
