# Generated by Django 5.2.8 on 2025-11-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_descripcion_descuento_venta_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descripcion_descuento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
